---
title: "Fischer_implementation"
output: html_document
date: "2025-08-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
getwd()
```

```{r}
library(readxl)
library(dplyr)
library(stringr)
library(tibble)

clean_pfas_value <- function(x) {
  # Converts "1.03×10-6 ± 1.75×10-7" → numeric
  if (is.na(x) || x == "no hit") return(0)
  x_clean <- str_split_fixed(x, "±", 2)[,1]
  x_clean <- str_replace_all(x_clean, "×10", "e")
  return(as.numeric(x_clean))
}

load_pfas_parameters <- function(pfas_name, file_path = "es5c05473_si_001.xlsx") {
  # --- Table S7 ---
  S7 <- read_excel(file_path, sheet = "Table_S7")
  row_S7 <- S7 %>% filter(PFAS == pfas_name)
  K_ML    <- 10^as.numeric(str_extract(row_S7$logK_PL_w,   "[0-9.]+"))
  K_SA    <- 10^as.numeric(str_extract(row_S7$logK_SA_w,   "[0-9.]+"))
  K_Glob  <- 10^as.numeric(str_extract(row_S7$logK_Glob_W, "[0-9.]+"))
  K_FABP  <- 10^as.numeric(str_extract(row_S7$logK_FABP_W, "[0-9.]+"))
  K_SP    <- 10^as.numeric(str_extract(row_S7$logK_SP_W,   "[0-9.]+"))

  # --- Table S8 ---
  S8 <- read_excel(file_path, sheet = "Table_S8")
  row_S8 <- S8 %>% filter(PFAS == pfas_name)
  K_PL_w_mean <- as.numeric(row_S8$mean_PL_W)   # Optional if you need means
  # (Not used if S7 is already log10-based and cleaned)

  # --- Table S9 ---
  S9 <- read_excel(file_path, sheet = "Table_S9")
  row_S9 <- S9 %>% filter(PFAS == pfas_name)
  P_app       <- clean_pfas_value(row_S9$P_app)
  P_OATP1B2   <- clean_pfas_value(row_S9$P_OATP1B2)
  P_OATP2B1   <- clean_pfas_value(row_S9$P_OATP2B1)

  # --- Table S10 ---
  S10 <- read_excel(file_path, sheet = "Table_S10")
  row_S10 <- S10 %>% filter(PFAS == pfas_name)
  P_OAT1 <- clean_pfas_value(row_S10$P_OAT1)
  P_OAT2 <- clean_pfas_value(row_S10$P_OAT2)
  P_OAT3 <- clean_pfas_value(row_S10$P_OAT3)
  P_NTCP <- clean_pfas_value(row_S10$P_NTCP)

  # Return a named list of parameters
  list(
    K_ML = K_ML,
    K_SA = K_SA,
    K_Glob = K_Glob,
    K_FABP = K_FABP,
    K_SP = K_SP,
    P_app = P_app,
    P_OATP1B2 = P_OATP1B2,
    P_OATP2B1 = P_OATP2B1,
    P_OAT1 = P_OAT1,
    P_OAT2 = P_OAT2,
    P_OAT3 = P_OAT3,
    P_NTCP = P_NTCP
  )
}

```

```{r}
pfas_params <- load_pfas_parameters("PFOS")
print(pfas_params$K_SA)      # Serum albumin partition coeff
print(pfas_params$P_app)     # Passive membrane diffusion
```

```{r}
calculate_partition_coeffs <- function(physio, compound) {
  with(compound, {
    with(physio, {
      
      # Blood partition coefficient
      K_blood <- (V_water_blood / V_blood) +
        (V_SA_blood / V_blood) * K_SA +
        (V_Glob_blood / V_blood) * K_Glob +
        (V_SP_blood / V_blood) * K_SP +
        (V_ML_blood / V_blood) * K_PL

      # Liver
      K_liver <- (V_water_liver / V_liver_tissue) +
        (V_FABP_liver / V_liver_tissue) * K_FABP +
        (V_SA_liver / V_liver_tissue) * K_SA +
        (V_SP_liver / V_liver_tissue) * K_SP +
        (V_ML_liver / V_liver_tissue) * K_PL

      # Bile
      K_bile <- (V_water_bile / V_bile) +
        (V_SA_bile / V_bile) * K_SA +
        (V_ML_bile / V_bile) * K_PL

      K_bile_liver <- K_bile / K_liver

      # Gut
      K_gut <- (V_water_gut / V_gut_tissue) +
        (V_FABP_gut / V_gut_tissue) * K_FABP +
        (V_SP_gut / V_gut_tissue) * K_SP +
        (V_ML_gut / V_gut_tissue) * K_PL +
        (V_SA_gut / V_gut_tissue) * K_SA

      # Kidneys
      K_kidneys <- (V_water_kidneys / V_kidneys_tissue) +
        (V_SA_kidneys / V_kidneys_tissue) * K_SA +
        (V_FABP_kidneys / V_kidneys_tissue) * K_FABP +
        (V_SP_kidneys / V_kidneys_tissue) * K_SP +
        (V_ML_kidneys / V_kidneys_tissue) * K_PL

      # Rest of body
      K_rest <- (V_water_rest / V_rest_tissue) +
        (V_FABP_rest / V_rest_tissue) * K_FABP +
        (V_SP_rest / V_rest_tissue) * K_SP +
        (V_ML_rest / V_rest_tissue) * K_PL +
        (V_SA_rest / V_rest_tissue) * K_SA

      return(list(
        K_blood = K_blood,
        K_liver = K_liver,
        K_bile = K_bile,
        K_bile_liver = K_bile_liver,
        K_gut = K_gut,
        K_kidneys = K_kidneys,
        K_rest = K_rest
      ))
    })
  })
}
```

```{r}
calculate_free_bound_fractions <- function(physio, K_values) {
  with(physio, {
    with(K_values, {
      
      f_free_blood    <- 1 / (1 + K_blood   * V_sorb_blood   / V_water_blood)
      f_free_liver    <- 1 / (1 + K_liver   * V_sorb_liver   / V_water_liver)
      f_free_gut      <- 1 / (1 + K_gut     * V_sorb_gut     / V_water_gut)
      f_free_kidneys  <- 1 / (1 + K_kidneys * V_sorb_kidneys / V_water_kidneys)
      f_free_rest     <- 1 / (1 + K_rest    * V_sorb_rest    / V_water_rest)
      f_free_filtrate <- f_free_blood # assume same as blood
      
      f_bound_blood    <- 1 - f_free_blood
      f_bound_liver    <- 1 - f_free_liver
      f_bound_gut      <- 1 - f_free_gut
      f_bound_kidneys  <- 1 - f_free_kidneys
      f_bound_rest     <- 1 - f_free_rest

      return(list(
        f_free_blood = f_free_blood,
        f_bound_blood = f_bound_blood,
        f_free_liver = f_free_liver,
        f_bound_liver = f_bound_liver,
        f_free_gut = f_free_gut,
        f_bound_gut = f_bound_gut,
        f_free_kidneys = f_free_kidneys,
        f_bound_kidneys = f_bound_kidneys,
        f_free_rest = f_free_rest,
        f_bound_rest = f_bound_rest,
        f_free_filtrate = f_free_filtrate
      ))
    })
  })
}

```


```{r}
set_initial_conditions <- function(physio, f_free_blood, f_bound_blood) {
  V_blood <- physio$V_blood
  C_blood_t0 <- 0 / V_blood
  list(
    yini = c(
      C_free_blood = C_blood_t0 * f_free_blood,
      C_bound_blood = C_blood_t0 * f_bound_blood,
      # Repeat other compartments, all mostly 0 or initial gut dose
    )
  )
}

```

```{r}
run_simulation <- function(physio, compound, yini, t_end) {
  times <- seq(0, t_end, length.out = 1000)
  out <- ode(times = times, y = yini, func = function(t, y, parms) {
    rigidode(t, y, c(physio, compound))
  }, parms = NULL, method = "lsoda")
  as.data.frame(out)
}

```

```{r}
simulate_pfas <- function(pfas_name, file_path = "supplementary_tables.xlsx") {
  # Load physiological parameters
  physio <- load_physiological_parameters()

  # Load compound-specific parameters from Excel
  compound <- load_pfas_parameters(pfas_name, file_path)

  # Calculate partition coefficients across tissues
  part_coeffs <- calculate_partition_coeffs(physio, compound)

  # Estimate free and bound fraction in blood (example calc, adjust as needed)
  f_free_blood <- 1 / (1 + part_coeffs$K_blood * 0.2 / 0.8)
  f_bound_blood <- 1 - f_free_blood

  # Set initial conditions
  yini_list <- set_initial_conditions(physio, f_free_blood, f_bound_blood)

  # Run the simulation
  results <- run_simulation(physio, compound, yini_list$yini, physio$t_end)

  return(results)
}

```

```{r}
initialize_pfas_model <- function(pfas_name,
                                  file_path = "es5c05473_si_001.xlsx",
                                  physio,
                                  bw = 30,                         # g
                                  V_blood = 1.0068,               # cm3
                                  V_gut_lumen = 3.15,             # cm3
                                  total_IV_dose_mg_kg = 0,
                                  total_oral_dose_mg_kg = 1000,
                                  daily_IV_dose_mg_kg_day = 0,
                                  daily_oral_dose_mg_kg_day = 0) {

  library(readxl)

  #--- 1. Load Data for Given PFAS from All Tables ---#
  logK_data <- read_excel(file_path, sheet = "Table_S7") %>% filter(PFAS == pfas_name)
  P_data    <- read_excel(file_path, sheet = "Table_S9") %>% filter(PFAS == pfas_name)
  OAT_data  <- read_excel(file_path, sheet = "Table_S10") %>% filter(PFAS == pfas_name)

  # Handle conversion of logK to K
  K_FABP <- 10^as.numeric(gsub("±.*", "", logK_data$logK_FABP_W))
  K_SA   <- 10^as.numeric(gsub("±.*", "", logK_data$logK_SA_w))
  K_Glob <- 10^as.numeric(gsub("±.*", "", logK_data$logK_Glob_W))
  K_SP   <- 10^as.numeric(gsub("±.*", "", logK_data$logK_SP_W))
  K_ML   <- 10^as.numeric(gsub("±.*", "", logK_data$logK_PL_w))

  # Handle P values
  parse_p <- function(p) {
    if (grepl("no hit", p, ignore.case = TRUE)) return(0)
    p_clean <- gsub("±.*", "", p)
    p_clean <- gsub("×10", "e", p_clean)
    as.numeric(p_clean)
  }
  P_app      <- parse_p(P_data$P_app)
  P_OATP1B2  <- parse_p(P_data$P_OATP1B2)
  P_OATP2B1  <- parse_p(P_data$P_OATP2B1)
  P_OAT1     <- parse_p(OAT_data$P_OAT1)
  P_OAT2     <- parse_p(OAT_data$P_OAT2)
  P_OAT3     <- parse_p(OAT_data$P_OAT3)
  P_NTCP     <- parse_p(OAT_data$P_NTCP)

  #--- 2. Partition Coefficients ---#
  K_values <- calculate_partition_coeffs(physio, list(
    K_FABP = K_FABP,
    K_SA   = K_SA,
    K_Glob = K_Glob,
    K_SP   = K_SP,
    K_ML   = K_ML
  ))

  #--- 3. Free and Bound Fractions ---#
  f_values <- calculate_free_bound_fractions(physio, K_values)

  #--- 4. Doses and Initial Conditions ---#
  total_IV_dose     <- total_IV_dose_mg_kg * bw / 1000
  total_oral_dose   <- total_oral_dose_mg_kg * bw / 1000
  total_dose        <- total_IV_dose + total_oral_dose

  daily_IV_dose     <- daily_IV_dose_mg_kg_day * bw / 1000 / 86400
  daily_oral_dose   <- daily_oral_dose_mg_kg_day * bw / 1000 / 86400

  C_blood_t0        <- total_IV_dose / V_blood
  C_free_blood_t0   <- C_blood_t0 * f_values$f_free_blood * V_blood / physio$V_water_blood
  C_bound_blood_t0  <- C_blood_t0 * f_values$f_bound_blood * V_blood / physio$V_sorb_blood
  C_gut_lumen_t0    <- total_oral_dose / V_gut_lumen

  yini <- c(
    C_free_blood = C_free_blood_t0,
    C_bound_blood = C_bound_blood_t0,
    C_free_blood_liver = C_free_blood_t0,
    C_bound_blood_liver = C_bound_blood_t0,
    C_free_blood_liver_hep = 0,
    C_bound_blood_liver_hep = 0,
    C_free_blood_gut = C_free_blood_t0,
    C_bound_blood_gut = C_bound_blood_t0,
    C_free_blood_kidneys = C_free_blood_t0,
    C_bound_blood_kidneys = C_bound_blood_t0,
    C_free_blood_rest = C_free_blood_t0,
    C_bound_blood_rest = C_bound_blood_t0,
    C_free_liver = 0,
    C_bound_liver = 0,
    C_bile = 0,
    C_free_gut = 0,
    C_bound_gut = 0,
    C_free_kidneys = 0,
    C_bound_kidneys = 0,
    C_filtrate = 0,
    C_free_rest = 0,
    C_bound_rest = 0,
    C_gut_lumen = C_gut_lumen_t0,
    J_blood_to_filtrate = 0,
    J_liver_to_bile = 0,
    Excreted_feces = 0,
    Excreted_urine = 0,
    Absorbed_total = 0
  )

  return(list(
    K_values = K_values,
    f_values = f_values,
    P_values = list(
      P_app = P_app,
      P_OATP1B2 = P_OATP1B2,
      P_OATP2B1 = P_OATP2B1,
      P_OAT1 = P_OAT1,
      P_OAT2 = P_OAT2,
      P_OAT3 = P_OAT3,
      P_NTCP = P_NTCP
    ),
    yini = yini,
    total_dose = total_dose,
    daily_IV_dose = daily_IV_dose,
    daily_oral_dose = daily_oral_dose
  ))
}

```

